apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      containers:
        - name: postgres
          image: my-postgres:v1
          imagePullPolicy: Never
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DATABASE
            - name: POSTGRES_IP
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_IP