apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-producer
  template:
    metadata:
      labels:
        app: my-producer
    spec:
      containers:
        - name: producer
          image: my-producer:v2
          imagePullPolicy: Never
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_URL
            - name: TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TOPIC_NAME
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GROUP_ID